name: cicd-pipeline-workflow 
on: 
    workflow_dispatch: 
    schedule: 
        -cron: "0 0 * * *"
jobs: 
    run-etl-pipeline: 
        runs-on: ubuntu-latest
        
        steps: 
            - name: Checkout repo content
              uses: actions/checkout@v2
              with: 
                token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
                
            - name: Setup Python
              uses: actions/setup-python@v2
              with: 
                python-version: '3.9'
                
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt 
              
            - name: Run data pipeline
              run: |
                  pip install jupyter nbconvert
                  jupyter nbconvert --to notebook -- execute process_ratings_reviews.ipynb -- output output.ipynb
              
            - name: Observe Data output
              run: |
                  cat output.ipynb
              
            - name: Check for changes 
              id: git-check 
              run: |
                git config user.name 'github-actions'
                git config user.email 'github-actions@github.com'
                git diff  --exit code || echo "changes=true" >> $GITHUB_ENV
                
            - name: Commit and push if changes 
              if: env.changes == 'true'
              run: |
                git add .
                git commit -m "Refresh data"
                git push
             
